channels:
- conda-forge
dependencies:
- python=3.11.11
- pip<=24.1.2
- pip:
  - mlflow==2.20.1
  - cloudpickle==3.1.1
  - cupy-cuda12x==13.3.0
  - cvxopt==1.3.2
  - dask==2024.10.0
  - graphviz==0.20.3
  - jaraco-collections==5.1.0
  - jinja2==3.1.5
  - matplotlib==3.7.5
  - numpy==1.26.4
  - pandas==2.1.4
  - pathlib==1.0.1
  - pyarrow==17.0.0
  - pycaret==3.3.2
  - pytest==8.3.4
  - python-snappy==0.7.3
  - scikit-learn==1.4.2
  - scipy==1.11.4
  - zstandard==0.23.0
name: mlflow-env
